name: CI Autofix

on:
  workflow_run:
    workflows: ["CI", "Auto-update PR branches"]
    types: [completed]

jobs:
  autofix:
    permissions:
      contents: write
      pull-requests: write
      issues: write
      actions: read
      id-token: write
      statuses: read
    uses: cheunjm/.github/.github/workflows/ci-autofix.yml@main
    with:
      format_fix_command: "npx prettier --write '**/*.{ts,tsx,md,json}'"
      lint_fix_command: "npx eslint --fix ."
      node_version: "20"
    secrets: inherit
